/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCourierRouteImport } from './routes/admin.courier'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as ShopWishlistRouteImport } from './routes/_shop.wishlist'
import { Route as ShopTrackOrderRouteImport } from './routes/_shop.track-order'
import { Route as ShopTermsRouteImport } from './routes/_shop.terms'
import { Route as ShopSizeGuideRouteImport } from './routes/_shop.size-guide'
import { Route as ShopShopRouteImport } from './routes/_shop.shop'
import { Route as ShopReturnPolicyRouteImport } from './routes/_shop.return-policy'
import { Route as ShopResetPasswordRouteImport } from './routes/_shop.reset-password'
import { Route as ShopPrivacyPolicyRouteImport } from './routes/_shop.privacy-policy'
import { Route as ShopOrderSuccessRouteImport } from './routes/_shop.order-success'
import { Route as ShopLoginRouteImport } from './routes/_shop.login'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as ShopAboutRouteImport } from './routes/_shop.about'
import { Route as ShopProductSlugRouteImport } from './routes/_shop.product.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCourierRoute = AdminCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTrackOrderRoute = ShopTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTermsRoute = ShopTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSizeGuideRoute = ShopSizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => ShopRoute,
} as any)
const ShopShopRoute = ShopShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ShopRoute,
} as any)
const ShopReturnPolicyRoute = ShopReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopResetPasswordRoute = ShopResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPrivacyPolicyRoute = ShopPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderSuccessRoute = ShopOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAboutRoute = ShopAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof ShopAboutRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/login': typeof ShopLoginRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/reset-password': typeof ShopResetPasswordRoute
  '/return-policy': typeof ShopReturnPolicyRoute
  '/shop': typeof ShopShopRoute
  '/size-guide': typeof ShopSizeGuideRoute
  '/terms': typeof ShopTermsRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof ShopAboutRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/login': typeof ShopLoginRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/reset-password': typeof ShopResetPasswordRoute
  '/return-policy': typeof ShopReturnPolicyRoute
  '/shop': typeof ShopShopRoute
  '/size-guide': typeof ShopSizeGuideRoute
  '/terms': typeof ShopTermsRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof ShopIndexRoute
  '/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_shop/about': typeof ShopAboutRoute
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/order-success': typeof ShopOrderSuccessRoute
  '/_shop/privacy-policy': typeof ShopPrivacyPolicyRoute
  '/_shop/reset-password': typeof ShopResetPasswordRoute
  '/_shop/return-policy': typeof ShopReturnPolicyRoute
  '/_shop/shop': typeof ShopShopRoute
  '/_shop/size-guide': typeof ShopSizeGuideRoute
  '/_shop/terms': typeof ShopTermsRoute
  '/_shop/track-order': typeof ShopTrackOrderRoute
  '/_shop/wishlist': typeof ShopWishlistRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/courier': typeof AdminCourierRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-success'
    | '/privacy-policy'
    | '/reset-password'
    | '/return-policy'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/about'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-success'
    | '/privacy-policy'
    | '/reset-password'
    | '/return-policy'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_shop'
    | '/admin'
    | '/_shop/about'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/login'
    | '/_shop/order-success'
    | '/_shop/privacy-policy'
    | '/_shop/reset-password'
    | '/_shop/return-policy'
    | '/_shop/shop'
    | '/_shop/size-guide'
    | '/_shop/terms'
    | '/_shop/track-order'
    | '/_shop/wishlist'
    | '/admin/categories'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/courier'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/settings'
    | '/_shop/'
    | '/_shop/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courier': {
      id: '/admin/courier'
      path: '/courier'
      fullPath: '/admin/courier'
      preLoaderRoute: typeof AdminCourierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/wishlist': {
      id: '/_shop/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/track-order': {
      id: '/_shop/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof ShopTrackOrderRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/terms': {
      id: '/_shop/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof ShopTermsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/size-guide': {
      id: '/_shop/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof ShopSizeGuideRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/shop': {
      id: '/_shop/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopShopRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/return-policy': {
      id: '/_shop/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof ShopReturnPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/reset-password': {
      id: '/_shop/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ShopResetPasswordRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/privacy-policy': {
      id: '/_shop/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof ShopPrivacyPolicyRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order-success': {
      id: '/_shop/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof ShopOrderSuccessRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/about': {
      id: '/_shop/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof ShopAboutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/product/$slug': {
      id: '/_shop/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopAboutRoute: typeof ShopAboutRoute
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopOrderSuccessRoute: typeof ShopOrderSuccessRoute
  ShopPrivacyPolicyRoute: typeof ShopPrivacyPolicyRoute
  ShopResetPasswordRoute: typeof ShopResetPasswordRoute
  ShopReturnPolicyRoute: typeof ShopReturnPolicyRoute
  ShopShopRoute: typeof ShopShopRoute
  ShopSizeGuideRoute: typeof ShopSizeGuideRoute
  ShopTermsRoute: typeof ShopTermsRoute
  ShopTrackOrderRoute: typeof ShopTrackOrderRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAboutRoute: ShopAboutRoute,
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopOrderSuccessRoute: ShopOrderSuccessRoute,
  ShopPrivacyPolicyRoute: ShopPrivacyPolicyRoute,
  ShopResetPasswordRoute: ShopResetPasswordRoute,
  ShopReturnPolicyRoute: ShopReturnPolicyRoute,
  ShopShopRoute: ShopShopRoute,
  ShopSizeGuideRoute: ShopSizeGuideRoute,
  ShopTermsRoute: ShopTermsRoute,
  ShopTrackOrderRoute: ShopTrackOrderRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCourierRoute: typeof AdminCourierRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCourierRoute: AdminCourierRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
