/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as ShopWishlistRouteImport } from './routes/_shop.wishlist'
import { Route as ShopTrackOrderRouteImport } from './routes/_shop.track-order'
import { Route as ShopShopRouteImport } from './routes/_shop.shop'
import { Route as ShopOrderSuccessRouteImport } from './routes/_shop.order-success'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as ShopProductSlugRouteImport } from './routes/_shop.product.$slug'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopWishlistRoute = ShopWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ShopRoute,
} as any)
const ShopTrackOrderRoute = ShopTrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => ShopRoute,
} as any)
const ShopShopRoute = ShopShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrderSuccessRoute = ShopOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductSlugRoute = ShopProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/shop': typeof ShopShopRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesByTo {
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/order-success': typeof ShopOrderSuccessRoute
  '/shop': typeof ShopShopRoute
  '/track-order': typeof ShopTrackOrderRoute
  '/wishlist': typeof ShopWishlistRoute
  '/': typeof ShopIndexRoute
  '/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shop': typeof ShopRouteWithChildren
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/order-success': typeof ShopOrderSuccessRoute
  '/_shop/shop': typeof ShopShopRoute
  '/_shop/track-order': typeof ShopTrackOrderRoute
  '/_shop/wishlist': typeof ShopWishlistRoute
  '/_shop/': typeof ShopIndexRoute
  '/_shop/product/$slug': typeof ShopProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/cart'
    | '/checkout'
    | '/order-success'
    | '/shop'
    | '/track-order'
    | '/wishlist'
    | '/'
    | '/product/$slug'
  id:
    | '__root__'
    | '/_shop'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/order-success'
    | '/_shop/shop'
    | '/_shop/track-order'
    | '/_shop/wishlist'
    | '/_shop/'
    | '/_shop/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/wishlist': {
      id: '/_shop/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof ShopWishlistRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/track-order': {
      id: '/_shop/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof ShopTrackOrderRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/shop': {
      id: '/_shop/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopShopRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/order-success': {
      id: '/_shop/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof ShopOrderSuccessRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/product/$slug': {
      id: '/_shop/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ShopProductSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopOrderSuccessRoute: typeof ShopOrderSuccessRoute
  ShopShopRoute: typeof ShopShopRoute
  ShopTrackOrderRoute: typeof ShopTrackOrderRoute
  ShopWishlistRoute: typeof ShopWishlistRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopProductSlugRoute: typeof ShopProductSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopOrderSuccessRoute: ShopOrderSuccessRoute,
  ShopShopRoute: ShopShopRoute,
  ShopTrackOrderRoute: ShopTrackOrderRoute,
  ShopWishlistRoute: ShopWishlistRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopProductSlugRoute: ShopProductSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
